#pragma once
#include <Arduino.h>
const char INDEX_HTML[] PROGMEM = R"PAGE(<!doctype html>
<html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Exilir IMU Logger</title><style>
*{box-sizing:border-box}body{font:17px system-ui,sans-serif;background:#f2f6f8;color:#162c40;margin:0;padding:24px 16px}main{max-width:560px;margin:auto}h1{font-size:27px;margin-bottom:4px}.card{background:white;border-radius:18px;padding:20px;margin:18px 0;box-shadow:0 4px 20px #162c4010}label{display:block;margin:15px 0 6px}input,select,button{font:inherit;width:100%;padding:12px;border:1px solid #cdd9df;border-radius:10px}button{cursor:pointer;background:#147d92;color:white;border:0;font-weight:600;margin-top:12px}button:disabled{opacity:.4;cursor:default}#stop{background:#d64e34}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}#phase{font-size:24px;font-weight:700;margin:8px 0}#message{color:#a53523;white-space:pre-wrap}small{display:block;color:#506878;line-height:1.5}a{color:#147d92}progress{width:100%;height:16px}</style>
<main><h1>Exilir IMU Logger</h1><small>Rekam gerakan langsung dari handphone.</small>
<div class="card"><div id="phase" aria-live="polite">Menghubungkan…</div><div style="font-size:32px;font-weight:700"><span id="steps">0</span> langkah</div><small id="detector"></small><div id="stats">Menunggu perangkat</div><progress id="progress" max="30" value="0"></progress><small id="quality"></small><p id="message" role="status"></p></div>
<div class="card"><label for="label">Nama rekaman / aktivitas</label><input id="label" value="walking_P01_S01" maxlength="32" pattern="[A-Za-z0-9_-]+" autocomplete="off"><label for="duration">Durasi total (termasuk 3 detik diam)</label><select id="duration"><option value="10">10 detik</option><option value="23" selected>23 detik: 3 diam + 20 aktivitas</option><option value="30">30 detik</option></select><div class="row"><button id="start" disabled>Start</button><button id="stop" disabled>Stop</button></div><small>Setelah Start, diam 3 detik. Bergerak saat status AKTIVITAS muncul. Cue pada HP dapat terlambat; waktu CSV berasal dari sensor.</small></div>
<div class="card"><strong>Unduh setelah rekaman berhenti</strong><button id="download" disabled>Download CSV — akselerasi</button><button id="download6" disabled>Download CSV — akselerasi + gyro</button><button id="metadata" disabled>Download metadata</button><small>CSV mencakup baseline. Akselerasi: m/s²; gyro: rad/s; timestamp: ms. Data disimpan sementara dan hilang jika perangkat dimatikan atau di-reset.</small></div></main>
<script>
let latest=null,busy=false,downloading=false;
const el=id=>document.getElementById(id);
function render(s){latest=s;el('steps').textContent=s.steps??0;el('detector').textContent=s.calibration_failed?'Baseline gagal: ulangi rekaman sambil diam.':!s.detector_ready?'Counter menunggu baseline 3 detik.':`Threshold ${s.high_m_s2.toFixed(1)} / ${s.low_m_s2.toFixed(1)} m/s² · jeda ${s.min_interval_ms} ms · baseline ${s.baseline_m_s2.toFixed(2)} m/s²`;const ready=s.sensor_ready&&s.sampler_ready;el('phase').textContent=!ready?'Sensor belum siap':s.recording?(s.elapsed_ms<3000?'DIAM — baseline':'AKTIVITAS — mulai bergerak'):(s.samples?'Rekaman selesai':'Siap merekam');el('stats').textContent=`${s.samples} sampel · ${(s.elapsed_ms/1000).toFixed(1)} detik · ${s.target_hz} Hz target`;el('progress').max=s.limit_ms/1000;el('progress').value=s.elapsed_ms/1000;el('quality').textContent=`Jeda maksimum: ${s.max_interval_ms.toFixed(2)} ms · slot terlewat: ${s.missed_slots} · ${s.reason}`;el('start').disabled=busy||downloading||!ready||s.recording;el('stop').disabled=busy||downloading||!s.recording;for(const id of ['download','download6','metadata'])el(id).disabled=busy||downloading||s.recording||!s.samples;el('label').disabled=s.recording||busy;el('duration').disabled=s.recording||busy;}
async function refresh(){if(downloading)return;try{const r=await fetch('/status',{cache:'no-store'});if(!r.ok)throw Error('Status perangkat tidak tersedia');render(await r.json());}catch(e){el('phase').textContent='Koneksi terputus';for(const id of ['start','stop','download','download6','metadata'])el(id).disabled=true;el('message').textContent='Hubungkan kembali ke Wi-Fi Exilir. Rekaman dapat tetap berjalan hingga batas durasi.';}}
async function command(path,params){busy=true;if(latest)render(latest);el('message').textContent='';try{const r=await fetch(path,{method:'POST',body:new URLSearchParams(params)});if(!r.ok)throw Error(await r.text());}catch(e){el('message').textContent=e.message;}finally{busy=false;await refresh();}}
el('start').onclick=()=>{const label=el('label').value.trim();if(!/^[A-Za-z0-9_-]{1,32}$/.test(label)){el('message').textContent='Nama: 1–32 huruf, angka, _ atau -.';return;}if(latest?.samples&&!confirm('Mulai rekaman baru akan mengganti data sebelumnya. Sudah diunduh?'))return;command('/start',{label,duration:el('duration').value,replace:'1'});};
el('stop').onclick=()=>command('/stop',{});
async function download(path,fallback){downloading=true;if(latest)render(latest);el('message').textContent='Menyiapkan unduhan…';try{const r=await fetch(path);if(!r.ok)throw Error(await r.text());const blob=await r.blob();const file=(r.headers.get('Content-Disposition')||'').match(/filename="([^"]+)"/);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file?file[1]:fallback;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),60000);el('message').textContent='Unduhan dikirim ke browser. Periksa folder Downloads / File di HP.';}catch(e){el('message').textContent=e.message;}finally{downloading=false;await refresh();}}
el('download').onclick=()=>download('/download?axes=3','acceleration.csv');el('download6').onclick=()=>download('/download?axes=6','imu.csv');el('metadata').onclick=()=>download('/metadata','metadata.json');
async function poll(){await refresh();setTimeout(poll,1000);}poll();
</script></html>)PAGE";
